apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: co2-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: co2_emission
      target:
        type: AverageValue
        averageValue: 21m